name: Log to Server

on:
  push:
    branches:
      - master  # 替换为您要监控的分支

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Add server to known_hosts
        run: ssh-keyscan -H 14.103.47.239 >> ~/.ssh/known_hosts

      - name: Write log to server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no asapp@14.103.47.239 "echo 'New update pushed at $(date)' >> /home/asapp/githubTest/logfile.log"
